global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers: 
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "web"

certificatesResolvers: 

cat << 'EOF' > traefik/traefik.yml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers: 
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "web"

certificatesResolvers: 
  letsencrypt:

  acme:
    email: "aym-sec-engineer@proton.me"
    storage: "/acme.json"
    httpChallenge:
      entryPoint: web
