---
- name: Politique UFW par défaut (Deny Incoming)
  ufw:
    direction: incoming
    default: deny

- name: Politique UFW par défaut (Allow Outgoing)
  ufw:
    direction: outgoing
    default: allow

- name: Autoriser le port SSH sécurisé 22222
  ufw:
    rule: allow
    port: '22222'
    proto: tcp

- name: Autoriser HTTP et HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'

- name: Activer UFW
  ufw:
    state: enabled
