---
- name: Configuration du port SSH dans 99-hardening.conf
  copy:
    dest: /etc/ssh/sshd_config.d/99-hardening.conf
    content: |
      Port 22222
      PermitRootLogin no
      PasswordAuthentication no
      PubkeyAuthentication yes
    mode: '0644'
  notify: Restart SSH

- name: Anti-spoofing sysctl
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '1'
    state: present
    reload: yes

- name: Log des paquets martiens sysctl
  sysctl:
    name: net.ipv4.conf.default.log_martians
    value: '1'
    state: present
    reload: yes
