name: Marley DevSecOps CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Validation de la syntaxe Docker Compose
        run: |
          docker compose config > /dev/null
          echo "✅ La syntaxe du fichier docker-compose.yml est valide !"
