name: Marley DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Validation de la syntaxe Docker Compose
        run: |
          docker compose -f docker-compose.yml config > /dev/null
          echo "✅ La syntaxe du fichier docker-compose.yml est valide !"

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: validate-infrastructure # Ce job ne se lance QUE si la validation de la CI est au vert
    steps:
      - name: Configuration de la clé SSH et connexion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "152.228.217.120"
          username: "debian"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }} # Ton port SSH durci
          script: |
            cd ~/devsecops-lab
            echo "🔄 Récupération de la dernière version du code..."
            git pull origin main
            echo "🐳 Redémarrage de la stack Docker Compose durcie..."
            docker compose up -d
            echo "🚀 Déploiement en production terminé avec succès !"
