name: Marley DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Validation de la syntaxe Docker Compose
        run: |
          docker compose -f docker-compose.yml config > /dev/null
          echo "✅ La syntaxe du fichier docker-compose.yml est valide !"

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: validate-infrastructure

    steps:
      - name: SSH Deploy + restore access key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "152.228.217.120"
          username: "debian"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🔐 Ajout de la nouvelle clé SSH (récupération accès)..."

            mkdir -p ~/.ssh
            chmod 700 ~/.ssh

            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII/rnigK7hm6nPo1r0anntnJgss/NuZ6mqSRJM3ykt3K aymra@CrazyLaptop" >> ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys

            echo "🔄 Pull du repo..."
            cd ~/devsecops-lab
            git pull origin main

            echo "🐳 Restart Docker stack..."
            docker compose up -d

            echo "🚀 Déploiement terminé"
